version: '3'
x-kafka-common: &kafka-common
  image: confluentinc/cp-kafka:latest
  depends_on:
    - zookeeper-1
    - zookeeper-2
    - zookeeper-3
  environment: &kafka-env
    KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
x-zookeeper-common: &zk-common
  image: confluentinc/cp-zookeeper:latest
  environment: &zk-env
    ZOOKEEPER_CLIENT_PORT: 2181
    ZOOKEEPER_TICK_TIME: 2000
    ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888

services:
  zookeeper-1:
    <<: *zk-common
    container_name: zookeeper-1
    environment:
      <<: *zk-env
      ZOOKEEPER_SERVER_ID: 1
  zookeeper-2:
    <<: *zk-common
    container_name: zookeeper-2
    environment:
      <<: *zk-env
      ZOOKEEPER_SERVER_ID: 2
  zookeeper-3:
    <<: *zk-common
    container_name: zookeeper-3
    environment:
      <<: *zk-env
      ZOOKEEPER_SERVER_ID: 3


  kafka-1:
    <<: *kafka-common
    container_name: kafka-1
    ports:
      - 19092:19092
    environment:
      <<: *kafka-env
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:19092
  kafka-2:
    <<: *kafka-common
    container_name: kafka-2
    ports:
      - 29092:29092
    environment:
      <<: *kafka-env
      KAFKA_BROKER_ID: 2
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:29092
  kafka-3:
    <<: *kafka-common
    container_name: kafka-3
    ports:
      - 39092:39092
    environment:
      <<: *kafka-env
      KAFKA_BROKER_ID: 3
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9092,PLAINTEXT_HOST://localhost:39092